# Copy this to Streamlit Cloud secrets and fill in the value.
# DATABASE_URL should match your Prisma DATABASE_URL
DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/health_dashboard?schema=public"
